[package]
name = "graphql"
version = "0.1.0"
authors = ["Sebastian Porto <s@porto5.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
serde = "1.0"
futures = "0.1"
env_logger = "0.5"
serde_derive = "1.0"
serde_json = "1.0"
juniper = "0.10"
juniper_codegen = "0.10"

