[package]
name = "api"
version = "0.1.0"
authors = ["Sebastian Porto <s@porto5.com>"]

[dependencies]
actix = "0.7.0"
actix-web = "0.6.15"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.9.2"