app: save-up

tenant: sporto

service:
  name: save-up

provider:
  name: aws
  apiName: save-up-api
  stackName: save-up-api
  region: ap-southeast-2
  runtime: rust
  environment:
    SYSTEM_EMAIL: ${env:SYSTEM_EMAIL}

plugins:
  # this adds informs servleress to use
  # the serverless-rust plugin
  - serverless-rust
# creates one artifact for each function

package:
  individually: true

functions:
  hello:
    handler: hello
  mail:
    handler: mail
    events:
      - sns: emails
