AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KIC

Globals:
  Function:
    Timeout: 3

  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  resLambdaLocalCorsStub:
    Type: AWS::Serverless::Function
    Properties:
      Handler: corsOptions.handler
      Runtime: nodejs6.10
      FunctionName: !Sub "${paramEnvironment}${paramFeatureBranch}_${paramServiceName}_corsOptions"
      CodeUri: cors
      Timeout: 30
      Events:
        optionsForGraphQlPub:
          Type: Api
          Properties:
            # RestApiId: !Ref KicApi
            Path: /graphql-pub
            Method: OPTIONS
        optionsForGraphQlPriv:
          Type: Api
          Properties:
            # RestApiId: !Ref KicApi
            Path: /graphql-app
            Method: OPTIONS

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/hello/
      Handler: hello
      Runtime: go1.x
      FunctionName: Hello
      Description: "KIC GraphQl Public Server"
      Environment:
        Variables:
          API_SECRET:
          SYSTEM_JWT:
      Events:
        GraphQl:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  GraphQlPubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/graphql/
      Handler: graphql
      Runtime: go1.x
      FunctionName: KicPubGraphQlPub
      Description: "KIC GraphQl Public Server"
      Environment:
        Variables:
          API_SECRET:
          CLIENT_HOST:
          DATABASE_HOST:
          DATABASE_NAME:
          DATABASE_USER:
          DATABASE_PASS:
          SYSTEM_JWT:
      Events:
        GraphQl:
          Type: Api
          Properties:
            Path: /graphql-pub
            Method: post

  GraphQlAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/graphql/
      Handler: graphql
      Runtime: go1.x
      FunctionName: KicGraphQlApp
      Description: "KIC GraphQl App Server"
      Environment:
        Variables:
          API_SECRET:
          CLIENT_HOST:
          DATABASE_HOST:
          DATABASE_NAME:
          DATABASE_USER:
          DATABASE_PASS:
          SYSTEM_JWT:
      Events:
        GraphQl:
          Type: Api
          Properties:
            # RestApiId: !Ref KicApi
            Path: /graphql-app
            Method: post

  MigrateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/graphql/
      Handler: graphql
      Runtime: go1.x
      FunctionName: Migrate
      Description: "KIC GraphQl DB migrate"
      Environment:
        Variables:
          API_SECRET:
          CLIENT_HOST:
          DATABASE_HOST:
          DATABASE_NAME:
          DATABASE_USER:
          DATABASE_PASS:
          SYSTEM_JWT:
      Events:
        GraphQl:
          Type: Api
          Properties:
            # RestApiId: !Ref KicApi
            Path: /migrate
            Method: post


