AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    KIC


Globals:
    Function:
        Timeout: 3


Resources:

    GraphQlFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: graphql/bin/
            Handler: graphql
            Runtime: go1.x
            FunctionName: KicGraphQl
            Description: "KIC GraphQl Server"
            Environment:
                Variables:
                    DATABASE_URL:
            Events:
                GraphQl:
                    Type: Api
                    Properties:
                        Path: /graphql
                        Method: post


Outputs:

    KicGraphQlApi:
      Description: "API Gateway endpoint URL for Prod stage for KIC GraphQl function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/"

    KicGraphQlFunction:
      Description: "KIC GraphQl Lambda Function ARN"
      Value: !GetAtt KicGraphQlFunction.Arn

    KicGraphQlFunctionIamRole:
      Description: "Implicit IAM Role created for KIC GraphQl function"
      Value: !GetAtt KicGraphQlFunctionRole.Arn
