AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    KIC


Globals:
    Function:
        Timeout: 3

    Api:
        # enable CORS; to make more specific, change the origin wildcard
        # to a particular domain name, e.g. "'www.example.com'"
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"


Resources:

    resLambdaLocalCorsStub:
        Type: AWS::Serverless::Function
        Properties:
            Handler: corsOptions.handler
            Runtime: nodejs6.10
            FunctionName: !Sub "${paramEnvironment}${paramFeatureBranch}_${paramServiceName}_corsOptions"
            CodeUri: cors
            Timeout: 30
            Events:
                optionsForGraphQlPub:
                    Type: Api
                    Properties:
                        RestApiId: !Ref GraphQlPubFunction
                        Path: /graphql-pub
                        Method: OPTIONS
                optionsForGraphQlPriv:
                    Type: Api
                    Properties:
                        RestApiId: !Ref GraphQlPrivFunction
                        Path: /graphql
                        Method: OPTIONS

    GraphQlPubFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: bin/
            Handler: graphql
            Runtime: go1.x
            FunctionName: KicGraphQl
            Description: "KIC GraphQl Public Server"
            Environment:
                Variables:
                    API_SECRET:
                    DATABASE_URL:
                    SYSTEM_JWT:
            Events:
                GraphQl:
                    Type: Api
                    Properties:
                        Path: /graphql-pub
                        Method: post

    GraphQlPrivFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: bin/
            Handler: graphql
            Runtime: go1.x
            FunctionName: KicGraphQl
            Description: "KIC GraphQl Private Server"
            Environment:
                Variables:
                    API_SECRET:
                    DATABASE_URL:
                    SYSTEM_JWT:
            Events:
                GraphQl:
                    Type: Api
                    Properties:
                        Path: /graphql
                        Method: post

    GraphQlPrivFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: bin/
            Handler: migrate
            Runtime: go1.x
            FunctionName: KicMigrate
            Description: "KIC GraphQl DB migrate"
            Environment:
                Variables:
                    API_SECRET:
                    DATABASE_URL:
                    SYSTEM_JWT:
            Events:
                GraphQl:
                    Type: Api
                    Properties:
                        Path: /migrate
                        Method: post


    Mail:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: mail/
            Handler: app.handler
            Runtime: nodejs8.10
            Timeout: 10
            Environment:
                Variables:
                    SYSTEM_EMAIL: VALUE
            Events:
                Mail:
                    Type: Api
                    Properties:
                        Path: /mail
                        Method: get

Outputs:

    KicGraphQlApi:
        Description: "API Gateway endpoint URL for Prod stage for KIC GraphQl function"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/"

    KicGraphQlFunction:
        Description: "KIC GraphQl Lambda Function ARN"
        Value: !GetAtt KicGraphQlFunction.Arn

    KicGraphQlFunctionIamRole:
        Description: "Implicit IAM Role created for KIC GraphQl function"
        Value: !GetAtt KicGraphQlFunctionRole.Arn
